"""Accessibility and console hygiene in the served app.

Two failure modes that no other tier can see:

* **a11y** — a control with no accessible name, a contrast ratio the brand palette cannot carry, a
  table with no header association. These are invisible to every functional test (the button still
  clicks) and to line coverage, but they decide whether the demo is usable with a screen reader.
* **console errors** — a failed fetch, a Plotly exception inside a callback, a 404 on an asset. The
  page renders, the test suite is green, and something is broken in a way only the browser knows.

Scoped to `serious`/`critical` axe violations. `minor`/`moderate` findings on a Gradio-generated
DOM are largely outside this repo's control, and gating on them would make the suite fail for
reasons no change here could fix.
"""

from __future__ import annotations

import pytest

pytest.importorskip("playwright")
pytest.importorskip("axe_playwright_python")
from axe_playwright_python.sync_playwright import Axe  # noqa: E402
from playwright.sync_api import Page, expect  # noqa: E402

pytestmark = pytest.mark.browser

BLOCKING_IMPACTS = {"serious", "critical"}

# Rules excluded because the offending markup is generated by Gradio and cannot be changed from
# this repo — each is named with the component that produces it, so the list stays auditable and a
# Gradio upgrade that fixes one can be spotted. Anything NOT listed here is enforced, and the
# contrast rule deliberately stays enforced: it caught a real defect in our own palette
# (eyebrow #74808f at 4.01:1, below AA — fixed in BRAND.md v2).
EXCLUDED_RULES = {
    # Gradio renders its own landmark/region structure; controls living in bare <div>s are a
    # framework choice, not something this repo can restructure.
    "region",
    # <div class="tab-container visually-hidden" aria-hidden="true"> containing focusable <button>s
    # — Gradio's own tab strip duplicates the tabs for measurement.
    "aria-hidden-focus",
    # <div role="grid"> without the rowgroup/row children the role requires — Gradio's Dataframe.
    "aria-required-children",
    # Gradio's Dataframe ships a drop-target <button> nested inside another interactive element.
    "nested-interactive",
    # <div aria-label="Empty value"> — Gradio's empty-plot placeholder puts aria-label on a plain
    # div, where it is not a permitted attribute.
    "aria-prohibited-attr",
}


# Node-level exclusions for third-party widgets we embed but do not author. Filtering by NODE
# rather than by rule keeps the rule itself enforced everywhere else — excluding `link-name`
# wholesale would also have hidden our own header links losing their accessible names.
#
# `.modebar-btn`: Plotly's toolbar. Its logo is
#   <a href="https://plotly.com/" data-title="Produced with Plotly.js" class="modebar-btn ...">
# with no text and no aria-label, so WebKit derives no accessible name (Chromium does — this only
# surfaces on the cross-browser matrix). Plotly exposes `displaylogo:false` as a *config* option,
# which Gradio's gr.Plot does not pass through, so it cannot be removed from here.
THIRD_PARTY_NODE_MARKERS = ("modebar-btn",)


def _is_third_party(node: dict) -> bool:
    targets = " ".join(str(t) for t in node.get("target", []))
    return any(m in targets or m in node.get("html", "") for m in THIRD_PARTY_NODE_MARKERS)


def _violations(page: Page) -> list[dict]:
    """Blocking axe violations, minus documented framework rules and third-party nodes."""
    results = Axe().run(page)
    out = []
    for v in results.response["violations"]:
        if v["impact"] not in BLOCKING_IMPACTS or v["id"] in EXCLUDED_RULES:
            continue
        ours = [n for n in v["nodes"] if not _is_third_party(n)]
        if ours:
            out.append({**v, "nodes": ours})
    return out


def _format(violations: list[dict]) -> str:
    return "\n".join(
        f"  [{v['impact']}] {v['id']}: {v['help']} ({len(v['nodes'])} node(s))"
        f"\n    first: {v['nodes'][0]['html'][:160]}"
        for v in violations
    )


def _wait_for_download_buttons_to_settle(page: Page) -> None:
    """Block until the export buttons finish fading in, so contrast is measured on a settled DOM.

    The status text and the two ``gr.DownloadButton``s update in the same event, but the buttons
    animate: Gradio drops ``disabled`` immediately and then transitions opacity 0.5 -> 1 and the
    background from the panel grey to white over 0.2 s. axe exempts *disabled* controls from
    ``color-contrast``, so for the length of that transition the buttons are both eligible and
    half-faded, and ``#1f3a5f`` at ~55 % opacity over grey does not clear 4.5:1. Measured under
    WebKit at the instant the status text appeared: ``opacity 0.52-0.57``, settling to 1 within
    200 ms — with ``#1f3a5f`` on ``#ffffff`` (~10.4:1) once settled, so there is no real defect to
    fix, only a window in which the scan can catch a value no user ever sees.

    That window is what turned ``browser e2e (webkit)`` red on the #7 and #9 merge runs, both times
    naming ``<button class="sm secondary ...">Download CSV</button>``, while the same commits passed
    WebKit elsewhere. It cannot be reproduced locally: axe's own injection takes longer than the
    transition, so the scan always arrives late on a fast machine.
    """
    page.wait_for_function(
        "() => [...document.querySelectorAll('button')]"
        ".filter(b => b.textContent.includes('Download'))"
        ".every(b => getComputedStyle(b).opacity === '1')"
    )


def test_node_filter_matches_the_widget_it_documents() -> None:
    """Pin the third-party marker against the real node shape it was added for.

    Without this, a typo or a rename silently turns the filter into a no-op (every node becomes
    "ours" again and the suite goes red for a reason no change here can fix), or a broadened marker
    silently swallows our own nodes. Node HTML is copied from the axe output that motivated it.
    """
    plotly_logo = {
        "target": ["a.modebar-btn"],
        "html": '<a href="https://plotly.com/" class="modebar-btn plotlyjsicon modebar-btn--logo">',
    }
    assert _is_third_party(plotly_logo)

    # Our own markup must still be scanned — the filter is node-level, not rule-level.
    ours = {"target": ["#md-header a"], "html": '<a href="https://doi.org/10.1021/...">Paper</a>'}
    assert not _is_third_party(ours)


def test_landing_page_has_no_serious_axe_violations(page: Page, served_app_url: str) -> None:
    page.goto(served_app_url)
    page.wait_for_selector("#md-file")

    violations = _violations(page)
    assert not violations, "axe found blocking violations on load:\n" + _format(violations)


def test_results_state_has_no_serious_axe_violations(page: Page, served_app_url: str) -> None:
    """The post-Detect DOM is where the table and the plot appear — the half of the app that only
    exists after a callback, and therefore the half an on-load scan never reaches.
    """
    page.goto(served_app_url)
    page.locator("#md-file").wait_for()
    page.locator("#md-examples").get_by_role("button", name="guajazulene").click()
    # The input-check panel is the signal that the example file has actually landed; pressing
    # Detect before it does gives `predict` a None file (race, only lost on Firefox/WebKit).
    expect(page.locator("#md-check")).to_contain_text("Input check")
    page.get_by_role("button", name="Detect multiplets").click()
    expect(page.get_by_text("Detected", exact=False)).to_be_visible(timeout=30_000)
    _wait_for_download_buttons_to_settle(page)

    violations = _violations(page)
    assert not violations, "axe found blocking violations after Detect:\n" + _format(violations)


def test_simulate_tab_has_no_serious_axe_violations(page: Page, served_app_url: str) -> None:
    page.goto(served_app_url)
    page.get_by_role("tab", name="Simulate").click()
    expect(page.get_by_label("Phenotype")).to_be_visible()

    violations = _violations(page)
    assert not violations, "axe found blocking violations on Simulate:\n" + _format(violations)


def test_a_full_detect_journey_logs_no_console_errors(page: Page, served_app_url: str) -> None:
    """A silent JS exception leaves the page rendered and every functional assertion passing.

    Listeners are attached before `goto` so nothing thrown during initial load is missed.
    """
    errors: list[str] = []

    def _record(entry: str) -> None:
        # "ResizeObserver loop completed with undelivered notifications" fires when a resize
        # callback triggers another resize in the same frame. It is benign by construction — the
        # browser defers the remaining notifications to the next frame — and it originates in
        # Plotly/Gradio's responsive layout, not in this repo. WebKit surfaces it as an uncaught
        # pageerror where Chromium and Firefox do not, so it only appears on the cross-browser
        # matrix. Matched on the exact message so any *other* uncaught error still fails.
        if "ResizeObserver loop" in entry:
            return
        errors.append(entry)

    page.on("console", lambda m: _record(f"{m.type}: {m.text}") if m.type == "error" else None)
    page.on("pageerror", lambda e: _record(f"pageerror: {e}"))

    page.goto(served_app_url)
    page.locator("#md-file").wait_for()
    page.locator("#md-examples").get_by_role("button", name="guajazulene").click()
    # The input-check panel is the signal that the example file has actually landed; pressing
    # Detect before it does gives `predict` a None file (race, only lost on Firefox/WebKit).
    expect(page.locator("#md-check")).to_contain_text("Input check")
    page.get_by_role("button", name="Detect multiplets").click()
    expect(page.get_by_text("Detected", exact=False)).to_be_visible(timeout=30_000)

    assert not errors, "console errors during the Detect journey:\n  " + "\n  ".join(errors)


def test_header_links_point_at_live_resources(page: Page, served_app_url: str) -> None:
    """The three header links are the app's only outbound claims — the paper DOI, the repo, the
    scope doc. Asserted structurally (no network call, so the browser tier stays offline-safe);
    a broken *target* is caught by the link checker, a broken *href* is caught here.
    """
    page.goto(served_app_url)
    page.wait_for_selector("#md-header")

    hrefs = page.eval_on_selector_all("#md-header a", "els => els.map(e => e.href)")
    assert any("doi.org/10.1021/acs.analchem.5c03465" in h for h in hrefs), hrefs
    assert any("github.com/smidooo/MolDeTr" in h for h in hrefs), hrefs
    assert any("SCOPE.md" in h for h in hrefs), hrefs
    assert all(h.startswith("https://") for h in hrefs), f"non-https header link: {hrefs}"
