"""Accessibility and console hygiene in the served app.

Two failure modes that no other tier can see:

* **a11y** — a control with no accessible name, a contrast ratio the brand palette cannot carry, a
  table with no header association. These are invisible to every functional test (the button still
  clicks) and to line coverage, but they decide whether the demo is usable with a screen reader.
* **console errors** — a failed fetch, a Plotly exception inside a callback, a 404 on an asset. The
  page renders, the test suite is green, and something is broken in a way only the browser knows.

Scoped to `serious`/`critical` axe violations. `minor`/`moderate` findings on a Gradio-generated
DOM are largely outside this repo's control, and gating on them would make the suite fail for
reasons no change here could fix.
"""

from __future__ import annotations

import pytest

pytest.importorskip("playwright")
pytest.importorskip("axe_playwright_python")
from axe_playwright_python.sync_playwright import Axe  # noqa: E402
from playwright.sync_api import Page, expect  # noqa: E402

pytestmark = pytest.mark.browser

BLOCKING_IMPACTS = {"serious", "critical"}

# Rules excluded because the offending markup is generated by Gradio and cannot be changed from
# this repo — each is named with the component that produces it, so the list stays auditable and a
# Gradio upgrade that fixes one can be spotted. Anything NOT listed here is enforced, and the
# contrast rule deliberately stays enforced: it caught a real defect in our own palette
# (eyebrow #74808f at 4.01:1, below AA — fixed in BRAND.md v2).
EXCLUDED_RULES = {
    # Gradio renders its own landmark/region structure; controls living in bare <div>s are a
    # framework choice, not something this repo can restructure.
    "region",
    # <div class="tab-container visually-hidden" aria-hidden="true"> containing focusable <button>s
    # — Gradio's own tab strip duplicates the tabs for measurement.
    "aria-hidden-focus",
    # <div role="grid"> without the rowgroup/row children the role requires — Gradio's Dataframe.
    "aria-required-children",
    # Gradio's Dataframe ships a drop-target <button> nested inside another interactive element.
    "nested-interactive",
    # <div aria-label="Empty value"> — Gradio's empty-plot placeholder puts aria-label on a plain
    # div, where it is not a permitted attribute.
    "aria-prohibited-attr",
}


def _violations(page: Page) -> list[dict]:
    """Blocking axe violations, minus the documented framework exclusions."""
    results = Axe().run(page)
    return [
        v
        for v in results.response["violations"]
        if v["impact"] in BLOCKING_IMPACTS and v["id"] not in EXCLUDED_RULES
    ]


def _format(violations: list[dict]) -> str:
    return "\n".join(
        f"  [{v['impact']}] {v['id']}: {v['help']} ({len(v['nodes'])} node(s))"
        f"\n    first: {v['nodes'][0]['html'][:160]}"
        for v in violations
    )


def test_landing_page_has_no_serious_axe_violations(page: Page, served_app_url: str) -> None:
    page.goto(served_app_url)
    page.wait_for_selector("#md-file")

    violations = _violations(page)
    assert not violations, "axe found blocking violations on load:\n" + _format(violations)


def test_results_state_has_no_serious_axe_violations(page: Page, served_app_url: str) -> None:
    """The post-Detect DOM is where the table and the plot appear — the half of the app that only
    exists after a callback, and therefore the half an on-load scan never reaches.
    """
    page.goto(served_app_url)
    page.locator("#md-file").wait_for()
    page.locator("#md-examples").get_by_role("button", name="guajazulene").click()
    page.get_by_role("button", name="Detect multiplets").click()
    expect(page.get_by_text("Detected", exact=False)).to_be_visible(timeout=30_000)

    violations = _violations(page)
    assert not violations, "axe found blocking violations after Detect:\n" + _format(violations)


def test_simulate_tab_has_no_serious_axe_violations(page: Page, served_app_url: str) -> None:
    page.goto(served_app_url)
    page.get_by_role("tab", name="Simulate").click()
    expect(page.get_by_label("Phenotype")).to_be_visible()

    violations = _violations(page)
    assert not violations, "axe found blocking violations on Simulate:\n" + _format(violations)


def test_a_full_detect_journey_logs_no_console_errors(page: Page, served_app_url: str) -> None:
    """A silent JS exception leaves the page rendered and every functional assertion passing.

    Listeners are attached before `goto` so nothing thrown during initial load is missed.
    """
    errors: list[str] = []
    page.on(
        "console", lambda m: errors.append(f"{m.type}: {m.text}") if m.type == "error" else None
    )
    page.on("pageerror", lambda e: errors.append(f"pageerror: {e}"))

    page.goto(served_app_url)
    page.locator("#md-file").wait_for()
    page.locator("#md-examples").get_by_role("button", name="guajazulene").click()
    page.get_by_role("button", name="Detect multiplets").click()
    expect(page.get_by_text("Detected", exact=False)).to_be_visible(timeout=30_000)

    assert not errors, "console errors during the Detect journey:\n  " + "\n  ".join(errors)


def test_header_links_point_at_live_resources(page: Page, served_app_url: str) -> None:
    """The three header links are the app's only outbound claims — the paper DOI, the repo, the
    scope doc. Asserted structurally (no network call, so the browser tier stays offline-safe);
    a broken *target* is caught by the link checker, a broken *href* is caught here.
    """
    page.goto(served_app_url)
    page.wait_for_selector("#md-header")

    hrefs = page.eval_on_selector_all("#md-header a", "els => els.map(e => e.href)")
    assert any("doi.org/10.1021/acs.analchem.5c03465" in h for h in hrefs), hrefs
    assert any("github.com/smidooo/MolDeTr" in h for h in hrefs), hrefs
    assert any("SCOPE.md" in h for h in hrefs), hrefs
    assert all(h.startswith("https://") for h in hrefs), f"non-https header link: {hrefs}"
